# Generated by Django 3.2.18 on 2023-05-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(),
        ),
    ]
