# Generated by Django 3.2.18 on 2023-05-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_booking', '0004_auto_20230501_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_comments',
            new_name='special_requests',
        ),
    ]
