# Generated by Django 3.2.18 on 2023-05-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_booking', '0005_rename_booking_comments_booking_special_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allergies',
        ),
        migrations.AddField(
            model_name='booking',
            name='allergies',
            field=models.CharField(blank=True, choices=[('milk', 'Milk'), ('eggs', 'Eggs'), ('fish', 'Fish (e.g., bass, flounder, cod)'), ('shellfish', 'Crustacean shellfish (e.g., crab, lobster, shrimp)'), ('nuts', 'Tree nuts (e.g., almonds, walnuts, pecans)'), ('peanuts', 'Peanuts'), ('wheat', 'Wheat'), ('soy', 'Soybeans'), ('sesame', 'Sesame')], default='', max_length=100),
        ),
    ]
