# Generated by Django 3.2.18 on 2023-05-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_booking', '0007_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=250),
        ),
    ]
