# Generated by Django 3.2.18 on 2023-05-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_booking', '0008_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='allergies',
        ),
    ]
